### ISSUE TITLE
please allow a way for the file to be renamed before upload

### ISSUE THREAD

**Issue by Suya1671** [itsmeow/curseforge-upload#1]
i would like an optional parameter which allows you to change the name of the .jar before upload,
e.g

with:
   token: ${{ secrets.CF_API_KEY }}
   project_id: ID
   game_endpoint: minecraft
   file_path: build/libs/modid-1.0.jar
   rename-file: mod.jar
   changelog: updated mod, changelog on github
   display_name: mod
   game_versions: 1.15.2,Java 8,Forge
   release_type: alpha

it will upload the exact thing of modid-1.0.jar, but will rename it to jarm.jar and upload the renamed file

**Comment by itsmeow** [comment]
This is feature creep. Actions is an extremely dynamic platform. I'm sure there's an action that supports renaming files. Also, you need to set `archivesBaseName` in your buildscript properly and gradle will output the modid. If you set `version` it changes the version string. Sounds like you don't know how to use gradle.

**Comment by itsmeow** [comment]
In fact, you don't even need an action to do this. This can be done with simple command exec actions and `mv`
