### ISSUE TITLE
CurseForge API is returning 400: Bad Request

### ISSUE THREAD

**Issue by klikli-dev** [itsmeow/curseforge-upload#10]
Sorry to open an issue - I'm aware this is not a problem of curseforge-upload, but I'm hoping to find out what the reason might be (seeing as that the API returns no error information).

[This workflow file](https://github.com/klikli-dev/occultism/actions/runs/1654680866/workflow)  at [this step](https://github.com/klikli-dev/occultism/runs/4704972415?check_suite_focus=true#step:10:1 ) leads to the error. 

![image](https://user-images.githubusercontent.com/60774993/148098564-200aa750-d4e5-4569-b34d-b67a325327b0.png)

Manually uploading the same file with the same settings via the CurseForge website works.

Interestingly, [this very similar workflow file](https://github.com/klikli-dev/occultism/actions/runs/1643940049/workflow) at [the same step](https://github.com/klikli-dev/occultism/runs/4680141313?check_suite_focus=true#step:10:1), works without issue as well.

![image](https://user-images.githubusercontent.com/60774993/148098754-6cf7679c-c2a5-49a7-9381-ba15e315e0a9.png)

Any ideas on what might be going wrong, or how to find out, would be appreciated.

Thank you!

**Comment by itsmeow** [comment]
Try requesting the endpoint manually

**Comment by itsmeow** [comment]
You can also try enabling debug output mode (google it, there's some secret you create and it will output more)

**Comment by klikli-dev** [comment]
Thanks for the input - debug output mode did not yield any additional info from the api response, but does show the metadata the step sends which is useful for manual testing.

Question in that regard: When sending a POST request to the file upload api as per https://support.curseforge.com/en/support/solutions/articles/9000197321-curseforge-api it returns html from the curseforge page. When sending GET to the game versions api it works. Do you have any ideas (from developing this github action) what might be going wrong?

**Comment by itsmeow** [comment]
These are the options the Action uses.
```
const options = {
    method: "POST",
    url: "https://" + endpoint + ".curseforge.com/api/projects/" + projectId + "/upload-file",
    port: 443,
    headers: {
        "Content-Type": "multipart/form-data",
        "X-Api-Token": token
    },
    formData: {
        "file": fs.createReadStream(filePath),
        "metadata": JSON.stringify(metadata)
    }
}
```

Not sure why that's happening, it's been quite a while since I used the API.

**Comment by klikli-dev** [comment]
Thanks!

Coming back to the original issue, this may after all be an issue with curseforge-upload, or rather with 1.18 content on curseforge.

I forked your repo to add some more debug output, and it turns out an [invalid game version ID is being used in the request](https://github.com/klikli-dev/occultism/runs/4735693072?check_suite_focus=true#step:10:242), namely 8849, 8897 and 8899 for 1.18.x versions.

It seems a few game version IDs of invalid gameVersionTypeID slip into the request when game versions 1.18 and 1.18.1 are used. Only gameVersionTypeID 73250 game versions are valid for Minecraft 1.18, but the request contains version ids of type 1 and type 615 in addition to 73250.

**Comment by itsmeow** [comment]
You did not namespace your game versions, that is why. You can PR the changes, but that is not actually an issue with the action.

You need to specify a namespace for Minecraft versions, because bukkit has its own namespace. Use `Minecraft 1.18:1.18` instead of `1.18`.

**Comment by klikli-dev** [comment]
I somehow managed to completely skip that in the documentation and from your sample - sorry! closing this now

**Comment by itsmeow** [comment]
v3.1.0 has improved the error handling natively, hopefully that will help you out!

**Comment by itsmeow** [comment]
I've also much improved the documentation
