### ISSUE TITLE
Alternative way to get version IDs

### ISSUE THREAD

**Issue by RoinujNosde** [itsmeow/curseforge-upload#12]
When you are uploading/editing a file in CurseForge, there are several checkboxes to select the versions.
After using the browser inspect tool, I discovered that each checkbox has an attribute named "value", which corresponds to the game version ID.

![image](https://user-images.githubusercontent.com/6441328/155637294-5d439d35-e486-422b-8cae-55692775a344.png)

**Comment by itsmeow** [comment]
Nice, thanks for letting me know.
