### ISSUE TITLE
Invalid game version ID: The game version ID: 9016 belongs to an invalid dependency

### ISSUE THREAD

**Issue by altrisi** [itsmeow/curseforge-upload#13]
Is this curseforge api being bad, or is there some bug with version name -> id mapping? (or did we do something incorrectly?)

The workflow passed `1.18.2` to the action, seems like it was translated to that id then curseforge rejected it.

`{"errorCode":1009,"errorMessage":"Invalid game version ID: 9016 belongs to an invalid dependency."}`

This is the run that triggered it with all the inputs: https://github.com/gnembon/fabric-carpet/runs/5683187727?check_suite_focus=true (in the little arrow at line 1)

**Comment by itsmeow** [comment]
You need to namespace your id. `Minecraft 1.18:1.18.2`

1.18.2 maps to several invalid version IDs inside CurseForge's very messy version API.
