### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by Crec0** [itsmeow/curseforge-upload#14]
# Description

In case of an invalid `typeId`, the filter at 
https://github.com/itsmeow/curseforge-upload/blob/cc1334d4e8b417914e51121fb7d8fbd010bb8ac5/curseforge-upload.js#L66-L68 
returns an empty list. This empty list is not checked and therefore throws `TypeError: Cannot read properties of undefined (reading 'id')` at 
https://github.com/itsmeow/curseforge-upload/blob/cc1334d4e8b417914e51121fb7d8fbd010bb8ac5/curseforge-upload.js#L73

# Steps to reproduce

Use the `invalid:1.18.2` for `game_versions` property.

# Expected output

A meaning full error telling me I used invalid `typeId` and exit gracefully.

# Actual output

 `TypeError` crash

**Comment by itsmeow** [comment]
Will do, thanks for reporting!

**Comment by itsmeow** [comment]
The empty list **is** checked and should gracefully exit.

https://github.com/itsmeow/curseforge-upload/blob/cc1334d4e8b417914e51121fb7d8fbd010bb8ac5/curseforge-upload.js#L69-L71

See:
```js
> [].length != 1
true
```

**Comment by Crec0** [comment]
hmm weird. I am not sure what's causing it then.

I did the tracing before reporting (I may be wrong here):
> It's setting the `gameVersionNames["1.18.2"] = "1.18"` if you pass in `1.18:1.18.2` for `game_versions`
which then sets typeId = 1.18
then this `typeId` is compared with name and slug from various version-types which (for 1.18) is
```json
    {
        "id": 73250,
        "name": "Minecraft 1.18",
        "slug": "minecraft-1-18"
    },
```
> and this returns empty since there's no matchh 


Check the log for this failed run:
<https://github.com/gnembon/fabric-carpet/runs/5778641865?check_suite_focus=true>

Posting log here for ease of accessibility.
```
Error: Cannot evaluate version type id 1.18
Error: Cannot read properties of undefined (reading 'id')
/home/runner/work/_actions/itsmeow/curseforge-upload/v3/dist/index.js:11262
            "Converted version type " + typeId + " to " + result[0].id
                                                                    ^

TypeError: Cannot read properties of undefined (reading 'id')
    at /home/runner/work/_actions/itsmeow/curseforge-upload/v3/dist/index.js:11262:69
    at Array.filter (<anonymous>)
    at getGameVersions (/home/runner/work/_actions/itsmeow/curseforge-upload/v3/dist/index.js:11[24](https://github.com/gnembon/fabric-carpet/runs/5778641865?check_suite_focus=true#step:11:24)5:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/home/runner/work/_actions/itsmeow/curseforge-upload/v3/dist/index.js:11318:[26](https://github.com/gnembon/fabric-carpet/runs/5778641865?check_suite_focus=true#step:11:26))
```
its trying to read id property of undefined which is caused by accessing an empty array.
See:
```js
> results = [1,2,3].filter(v => v == null)
[]
> results[0].id
Uncaught TypeError: Cannot read properties of undefined (reading 'id')
>
```

**Comment by Crec0** [comment]
If the list were to contain empty object or an undefined object, it should silently return undefined and not raise an error
See:
```js
> {}.id
undefined
> [undefined].id
undefined
>
```

**Comment by Crec0** [comment]
Oh wait it does set the error. Just doesn't exit. Didn't notice it. Exception sidetracked me.
