### ISSUE TITLE
Feature: Modpack Serverpack Support

### ISSUE THREAD

**Issue by jqshuv** [itsmeow/curseforge-upload#15]
A feature that you also can upload the serverpack with it.

**Comment by itsmeow** [comment]
You should be able to, use the parent file ID field.

**Comment by jqshuv** [comment]
Ok, I'll try it tomorrow

**Comment by jqshuv** [comment]
> You should be able to, use the parent file ID field.

But how should I get the file ID in Github actions?

**Comment by itsmeow** [comment]
steps.(id of cf upload task, set this in the workflow).outputs.id

**Comment by jqshuv** [comment]
like this?
![image](https://user-images.githubusercontent.com/48137077/163733315-1fc0fa80-d6ba-43a4-8438-97ef56a0a4ea.png)

**Comment by itsmeow** [comment]
yes, if the id field on the previous upload workflow is "release-curseforge".

**Comment by jqshuv** [comment]
Thaks! It worked.
