### ISSUE TITLE
Don't bump major with dependency updates

### ISSUE THREAD

**Issue by altrisi** [itsmeow/curseforge-upload#3]
Bumping major (v2->v3) for dependency updates basically makes everyone that isn't targeting latest commit to get outdated versions of the action. Since Github recommends (and suggests the code for in the marketplace) tagging the release with a major in the action workflow, that's most of the users.

AFAIK, Github follows semver, which basically means that you should only bump major in case there are are "backwards-incompatible changes", like changing required arguments, etc. Other changes (dep updates, fixes, small additions that don't break old workflows, etc) shouldn't bump major, but either minor or patch.

Don't worry about the v3 now, that one is already released, but please don't do it for the next versions, imagine the deps update include security issues or something more important, you would be letting users out.

Thanks!

You can close this.

**Comment by itsmeow** [comment]
Yeah, I get semver I just hadn't really done the project in way (1.0.0 vs v1) that it made sense for me to do versioning. Any future updates I will switch it to the three-part versioning system.

**Comment by altrisi** [comment]
Thanks!
