### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by florensie** [itsmeow/curseforge-upload#4]
Any idea what's going on here?
https://github.com/florensie/eggtab-fabric/runs/1644437249?check_suite_focus=true#step:9:22

**Comment by florensie** [comment]
Running the exact same job again and I got Bad Request instead, but this time on my second upload with the first file as parent.
https://github.com/florensie/eggtab-fabric/runs/1644496122?check_suite_focus=true#step:10:24

**Comment by itsmeow** [comment]
Your formatting is all screwy I think, the changelog part? Also I think the `+` symbol is not allowed in file names. Either way it's not really an issue of the Action itself but usage of the CF API- those errors are returned by the API, not my action. You can test stuff manually using something like Postman or curl and see if your requests go through.
