### ISSUE TITLE
Obtain value of changelog from file

### ISSUE THREAD

**Issue by shahab96** [itsmeow/curseforge-upload#5]
Is this currently possible? If so how would I go about doing that, otherwise could it be added?

**Comment by itsmeow** [comment]
You can use GitHub Actions workflows to do this. Learn how to use inputs and outputs. There should be a file read action somewhere on the marketplace.

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idoutputs
