### ISSUE TITLE
Input file_path accept first found .jar in folder path

### ISSUE THREAD

**Issue by Macleykun** [itsmeow/curseforge-upload#7]
It would be handy if the file_path input would, if given only a path, to get the first occurrence of a .jar.
This way, people don't have to make an extra step to refer to the exact jar they want to upload.
If multiple .jar's are found, throw an warning but get the first occurrence.

You think this is a good idea?

**Comment by itsmeow** [comment]
Eh. I like what's in the example action more. I use gradle variables myself to control this, you can export fields from the build step using the echo API of github actions.

**Comment by Macleykun** [comment]
What? Which variables? From actions/setup-java@v2 ?

**Comment by itsmeow** [comment]
@Macleykun Apologies, I didn't see your reply until now. You can export variables from your Gradle buildscript into the GitHub actions step by using the echo API. Here's an example of me doing it: https://maven.itsmeow.dev/scripts/alphas.gradle
You can then reference those by using the ID of the step that runs the gradle build, just make sure you add an `id` to that step.
https://github.com/itsmeow/betteranimalsplus/blob/8088b11a1b1eb160ed676c7499c8e96686f90714/.github/workflows/gradle-releases.yml

**Comment by Macleykun** [comment]
Sorry for the late reply!
Thank you! I now get it :D it's in gradle buildscript which makes alot of sense now!
