### ISSUE TITLE
CurseForge API is returning 400: Bad Request

### ISSUE THREAD

**Issue by oddstr13** [itsmeow/curseforge-upload#9]
I'm not sure which request is failing, as the logging isn't detailed enough.
The response body would likely say exactly why the request failed, but isn't printed.

https://github.com/oddstr13/MinecartMeter/runs/4655726066?check_suite_focus=true#step:10:18

https://github.com/oddstr13/MinecartMeter/blob/a5fec276f80df081cfd7fe4b68e629f6064d9208/.github/workflows/publish.yml#L83-L94

**Comment by itsmeow** [comment]
You are requesting the `minecraft` game endpoint, I believe you intended to request `bukkit`.

**Comment by oddstr13** [comment]
As far as I can tell, the versions endpoint is correct, but I guess it's possible that it wants a different upload endpoint?

**Comment by itsmeow** [comment]
![image](https://user-images.githubusercontent.com/10366817/147825756-ceb534fc-b209-4ded-afaf-11971da95d5f.png)
See highlighted text. It is attempting an upload to the minecraft endpoint.

**Comment by itsmeow** [comment]
![image](https://user-images.githubusercontent.com/10366817/147825776-00ac6b33-f052-4d46-a38c-416b751ef005.png)
Change this to bukkit.

**Comment by itsmeow** [comment]
`${{ env.minecraft_api }}` would do it.

**Comment by itsmeow** [comment]
As a side note, this isn't really an issue with the action - the endpoint returns 400 Bad Request, that's all my action knows. CurseForge's API has pretty weak error handling.
